## Fisrst draft

In [51]:
%pwd

'/home/sebair/CEU-Capstone-Project'

In [49]:
#importing dependecies
import pandas as pd

I am using the spredsheet from national grid which can be found 
<a href = "https://www.nationalgrideso.com/document/5073 /download"> here </a> and I took screenshot of the spreadsheet, which can be seen below. I will use pandas for reading, so I will use the pandas read_excel function, however I will need to define the sheet_names, each sheet is for one year data .

<img src = "pics/worksheet.png" alt = "pic from screenshot">

From here we can see that the 2005 t0 2009 the sheet names are without the keyword "Dem"

In [56]:
#creating names
years = ["Dem "+ str(i)+"-"+str(i%100 + 1) for i in range(2005,2020)]

In [57]:
for i in range(len(years)):
    #last two digits of the years list
    temp = years[i].split("-")
    #the sheet names are of the form 2005-06
    if int(temp[1]) < 10:
        #the sheet for the years between 2005 and 2008 they
        #do not have the string "Dem"
        new_sheet_name = temp[0].split(" ")[1] + "-0" + temp[1]
        years[i] = new_sheet_name

In [58]:
years

['2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 'Dem 2009-10',
 'Dem 2010-11',
 'Dem 2011-12',
 'Dem 2012-13',
 'Dem 2013-14',
 'Dem 2014-15',
 'Dem 2015-16',
 'Dem 2016-17',
 'Dem 2017-18',
 'Dem 2018-19',
 'Dem 2019-20']

I think these names should be fine

## Now I will only read the demand tariffs

In [131]:
sheets = pd.read_excel("TNUoS Tariffs 2005-06 to 2019-20.xlsx",
                   sheet_name= years,
                        # skip the first 5 rows because they are empty anyway
                       skiprows=5)

Each sheet is pandas dataframe, this is one example.

In [132]:
#this is for 2005
sheets[years[0]]

,Zone No.,Zone Name,Zonal Tariff (£/kW),Unnamed: 3,Zone No..1,Zone Name.,HH Zonal Tariff (£/kW),NHH Zonal Tariff (p/kWh)
0,1,Peterhead,18.162236,NaN,1.0,Northern Scotland,0.041110,0.005610
1,2,North Scotland,20.929759,NaN,2.0,Southern Scotland,4.114438,0.561693
2,3,Skye,23.095483,NaN,3.0,Northern,7.393664,0.970234
3,4,Western Highland,18.920247,NaN,4.0,North West,11.137060,1.461966
4,5,Central Highlands,15.360647,NaN,5.0,Yorkshire,11.182059,1.487585
5,6,Cruachan,15.852828,NaN,6.0,N Wales & Mersey,11.210216,1.512416
6,7,Argyll,13.441972,NaN,7.0,East Midlands,13.465848,1.804975
7,8,Stirlingshire,12.610665,NaN,8.0,Midlands,15.026957,2.062601
8,9,South Scotland,11.820471,NaN,9.0,Eastern,14.028455,1.909865
9,10,North East England,8.090616,NaN,10.0,South Wales,18.315906,2.368863
10,11,"Humber, Lancashire & SW Scotland",4.906290,NaN,11.0,South East,15.989410,2.167559
11,12,Anglesey,6.122706,NaN,12.0,London,18.516693,2.454909
12,13,Dinorwig,8.705520,NaN,13.0,Southern,17.833397,2.446575
13,14,South Yorks & North Wales,3.120190,NaN,14.0,South Western,20.489868,2.728435
14,15,Midlands & South East,1.322966,NaN,NaN,NaN,NaN,NaN
15,16,Central London,-5.712196,NaN,NaN,Demand tariffs include a 'small generators' ad...,0.041110,0.005610
16,17,North London,-0.220327,NaN,NaN,NaN,NaN,NaN
17,18,Oxon & South Coast,-0.698936,NaN,NaN,NaN,NaN,NaN
18,19,South Wales & Gloucester,-2.552479,NaN,NaN,NaN,NaN,NaN
19,20,Wessex,-4.951295,NaN,NaN,NaN,NaN,NaN
20,21,Peninsula,-8.044943,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Residual Charge for Generation (£/kW),NaN,3.257000,NaN,NaN,NaN,NaN,NaN
23,Residual Charge for Demand (£/kW),NaN,11.190000,NaN,NaN,NaN,NaN,NaN

From 2005 to 2009 the demand and generator tariffs(I assume, I will need a second check from you) are on the same spreadsheet so I have to separate them(filter them out)

Below is the dataframe for 2005

In [133]:
for i,j in sheets.items():
    try:
        if int(i.split("-")[0]) <= 2008:
            print("This is for",i)
            print( sheets[i][sheets[i].columns[4:]][0:28])
            print("---------------------------------------")
            temp = sheets[i][sheets[i].columns[4:]][0:28]
            
            sheets[i] = temp
    except:
        print("This is for the further years")
        pass

This is for 2005-06
    Zone No..1                                         Zone Name.  \
0          1.0                                  Northern Scotland
1          2.0                                  Southern Scotland
2          3.0                                           Northern
3          4.0                                         North West
4          5.0                                          Yorkshire
5          6.0                                   N Wales & Mersey
6          7.0                                      East Midlands
7          8.0                                           Midlands
8          9.0                                            Eastern
9         10.0                                        South Wales
10        11.0                                         South East
11        12.0                                             London
12        13.0                                           Southern
13        14.0                                      South Western
14         NaN                                                NaN
15         NaN  Demand tariffs include a 'small generators' ad...
16         NaN                                                NaN
17         NaN                                                NaN
18         NaN                                                NaN
19         NaN                                                NaN
20         NaN                                                NaN
21         NaN                                                NaN
22         NaN                                                NaN
23         NaN                                                NaN

    HH Zonal Tariff (£/kW)  NHH Zonal Tariff (p/kWh)
0                 0.041110                  0.005610
1                 4.114438                  0.561693
2                 7.393664                  0.970234
3                11.137060                  1.461966
4                11.182059                  1.487585
5                11.210216                  1.512416
6                13.465848                  1.804975
7                15.026957                  2.062601
8                14.028455                  1.909865
9                18.315906                  2.368863
10               15.989410                  2.167559
11               18.516693                  2.454909
12               17.833397                  2.446575
13               20.489868                  2.728435
14                     NaN                       NaN
15                0.041110                  0.005610
16                     NaN                       NaN
17                     NaN                       NaN
18                     NaN                       NaN
19                     NaN                       NaN
20                     NaN                       NaN
21                     NaN                       NaN
22                     NaN                       NaN
23                     NaN                       NaN
---------------------------------------
This is for 2006-07
    Zone No..1                                         Zone Name.  \
0      1.00000                                  Northern Scotland
1      2.00000                                  Southern Scotland
2      3.00000                                           Northern
3      4.00000                                         North West
4      5.00000                                          Yorkshire
5      6.00000                                   N Wales & Mersey
6      7.00000                                      East Midlands
7      8.00000                                           Midlands
8      9.00000                                            Eastern
9     10.00000                                        South Wales
10    11.00000                                         South East
11    12.00000                                             London
12    13.00000                                           Southern
13    14.00000                                      South Western
14         NaN                                                NaN
15         NaN  Demand tariffs include a 'small generators' ad...
16         NaN                                                NaN
17         NaN                                                NaN
18         NaN                                                NaN
19         NaN                                                NaN
20         NaN                                                NaN
21         NaN                                                NaN
22         NaN                                                NaN
23         NaN                                                NaN
24         NaN                                                NaN
25     3.55035                                                NaN
26    12.42538                                                NaN

    HH Zonal Tariff (£/kW)  NHH Zonal Tariff (p/kWh)
0                 0.496953                  0.062085
1                 5.489199                  0.727452
2                 8.492636                  1.149576
3                12.026138                  1.605120
4                12.046757                  1.646536
5                12.270131                  1.645144
6                14.562806                  1.993682
7                16.103361                  2.196657
8                15.141222                  2.107075
9                19.768764                  2.573303
10               17.948403                  2.481972
11               19.782022                  2.576423
12               19.430616                  2.673328
13               22.222076                  2.872320
14                     NaN                       NaN
15                0.051802                  0.006991
16                     NaN                       NaN
17                     NaN                       NaN
18                     NaN                       NaN
19                     NaN                       NaN
20                     NaN                       NaN
21                     NaN                       NaN
22                     NaN                       NaN
23                     NaN                       NaN
24                     NaN                       NaN
25                     NaN                       NaN
26                     NaN                       NaN
---------------------------------------
This is for 2007-08
    Zone No..1                                         Zone Name.  \
0     1.000000                                  Northern Scotland
1     2.000000                                  Southern Scotland
2     3.000000                                           Northern
3     4.000000                                         North West
4     5.000000                                          Yorkshire
5     6.000000                                   N Wales & Mersey
6     7.000000                                      East Midlands
7     8.000000                                           Midlands
8     9.000000                                            Eastern
9    10.000000                                        South Wales
10   11.000000                                         South East
11   12.000000                                             London
12   13.000000                                           Southern
13   14.000000                                      South Western
14         NaN                                                NaN
15         NaN  Demand tariffs include a 'small generators' ad...
16         NaN                                                NaN
17         NaN                                                NaN
18         NaN                                                NaN
19         NaN                                                NaN
20         NaN                                                NaN
21         NaN                                                NaN
22         NaN                                                NaN
23         NaN                                                NaN
24    3.866250                                                NaN
25   14.061505                                                NaN

    HH Zonal Tariff (£/kW)  NHH Zonal Tariff (p/kWh)
0                 1.445659                  0.183742
1                 6.362303                  0.830136
2                 9.884146                  1.287148
3                13.646168                  1.734890
4                13.615270                  1.750626
5                14.084355                  1.805802
6                16.370802                  2.129626
7                17.807318                  2.301762
8                17.060375                  2.240442
9                21.537451                  2.713949
10               20.076054                  2.586190
11               22.164365                  2.710106
12               21.100281                  2.738161
13               23.770560                  3.000403
14                     NaN                       NaN
15                0.055127                  0.007090
16                     NaN                       NaN
17                     NaN                       NaN
18                     NaN                       NaN
19                     NaN                       NaN
20                     NaN                       NaN
21                     NaN                       NaN
22                     NaN                       NaN
23                     NaN                       NaN
24                     NaN                       NaN
25                     NaN                       NaN
---------------------------------------
This is for 2008-09
    Zone No..1                                         Zone Name.  \
0     1.000000                                  Northern Scotland
1     2.000000                                  Southern Scotland
2     3.000000                                           Northern
3     4.000000                                         North West
4     5.000000                                          Yorkshire
5     6.000000                                   N Wales & Mersey
6     7.000000                                      East Midlands
7     8.000000                                           Midlands
8     9.000000                                            Eastern
9    10.000000                                        South Wales
10   11.000000                                         South East
11   12.000000                                             London
12   13.000000                                           Southern
13   14.000000                                      South Western
14         NaN                                                NaN
15         NaN  Demand tariffs include a 'small generators' ad...
16         NaN                                                NaN
17         NaN                                                NaN
18         NaN                                                NaN
19         NaN                                                NaN
20         NaN                                                NaN
21         NaN                                                NaN
22         NaN                                                NaN
23         NaN                                                NaN
24    4.108374                                                NaN
25   15.403402                                                NaN

    HH Zonal Tariff (£/kW)  NHH Zonal Tariff (p/kWh)
0                 2.869716                  0.372036
1                 7.950377                  1.049619
2                10.899023                  1.424364
3                14.911638                  1.956780
4                14.829178                  1.935788
5                15.460156                  2.036959
6                17.620712                  2.343048
7                19.147817                  2.543378
8                18.364952                  2.474431
9                23.230707                  2.940514
10               21.500870                  2.849708
11               23.548992                  3.013718
12               22.194810                  2.933872
13               25.212997                  3.217128
14                     NaN                       NaN
15                0.061298                  0.008062
16                     NaN                       NaN
17                     NaN                       NaN
18                     NaN                       NaN
19                     NaN                       NaN
20                     NaN                       NaN
21                     NaN                       NaN
22                     NaN                       NaN
23                     NaN                       NaN
24                     NaN                       NaN
25                     NaN                       NaN
---------------------------------------
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years
This is for the further years

In [148]:
residual_demand = sheets["2006-07"].loc[26][0]

12.42538018942641

In [151]:
sheets["2006-07"]["year"] = "2006"

# Quesion 1: In the spreadsheet there are demand and generator charges for years 2005 to 2008. For now the HH zonal tariff and NHH zonal tariff will be inputs. Which one should I take for the residual?